version: '3.8'

services:
  # Production service with Nginx
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pdf-takeoff
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Coolify will generate a FQDN for this service
      - SERVICE_FQDN_WEB
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
